sudo: false
cache:
  directories:
    - $HOME/.wheels

language: python
python: 3.6
dist: xenial

env:
  # generate with: tox -l
  - TOX_ENV=py35-django22
  - TOX_ENV=py36-django22
  - TOX_ENV=py37-django22
  - TOX_ENV=py37-django30
  - TOX_ENV=py37-django31
  - TOX_ENV=py38-django22
  - TOX_ENV=py38-django30
  - TOX_ENV=py38-django31
  - TOX_ENV=py39-django22
  - TOX_ENV=py39-django30
  - TOX_ENV=py39-django31
  - TOX_ENV=py310-django22
  - TOX_ENV=py310-django30
  - TOX_ENV=py310-django31
  - TOX_ENV=flake8
  - TOX_ENV=docs
  - TOX_ENV=coveralls

global:
  - PIP_WHEEL_DIR=$HOME/.wheels
  - PIP_FIND_LINKS=file://$PIP_WHEEL_DIR

install:
  - pip install tox

script:
  tox -e $TOX_ENV

notifications:
  email:
    on_success: never
    on_failure: change

